services:
  - type: web
    name: ebd-flask
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_entrypoint.sh
    envVars:
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ebd_postgres
          property: connectionString

databases:
  - name: ebd-postgres
    databaseName: ebd_postgres
    user: ebd_postgres_user
    plan: free
